# derived from Figure 14. published in:
#
# Page R (2023) Ten years and a million links: building a global taxonomic library connecting persistent
# identifiers for names, publications and people. Biodiversity Data Journal 11: e107914.
# https://doi.org/10.3897/BDJ.11.e107914
#
PREFIX schema: <http://schema.org/>
SELECT DISTINCT ?person ?person_name
# FROM <https://www.ipni.org>
# FROM <https://orcid.org>
WHERE {
?id schema:propertyID "RINGGOLD" .
?id schema:value "41803" .
?org schema:identifier ?id .
?person schema:affiliation ?org .
?work schema:creator ?person .
?taxonName schema:isBasedOn ?work .
?taxonName schema:name ?name .
{
?person schema:givenName ?givenName .
?person schema:familyName ?familyName .
BIND(CONCAT(?givenName, " ", ?familyName) AS ?person_name).

}
}
ORDER BY ?person_name
